### PR TITLE
DMDetector: support for Damaged DataMatrix

### PR DESCRIPTION
**Pull request by aiden-jiang**

### CODE REVIEW

**Comment by aiden-jiang** [comment]
Need to be modified

**Comment by aiden-jiang** [comment]
close

**Comment by axxel** [comment]
Sorry for not replying earlier (did not have the time to properly look at your code and test it). What do you mean by "close"?

**Comment by aiden-jiang** [comment]
Because I am not familiar with PR, the code is something wrong, I will re commit pr soon

**Comment by axxel** [comment]
I read your last comment this way: I shall close the PR, once you have something new/better, you open a new one.

**Pull request closed without merging**
