### PR TITLE
Implements symbologyIdentifier for Code 39 (#214)

### PR DESCRIPTION
**Pull request by gitlost**
Part-implements #214

Implements symbologyIdentifier for Code 39.

Adds unit test.

### CODE REVIEW

**Comment by gitlost** [comment]
This PR is ready for review.

**Comment by gitlost** [comment]
Force-push [ecf12a1](https://github.com/nu-book/zxing-cpp/pull/294/commits/ecf12a1fbea8d376001a0fb321a5afe6606bd711) added uniit test "ODCode39ReaderTest.cpp" to "test/unit/CMakeLists.txt"; also made `symbologyModifiers` array in `Code39Reader::decodePattern()` const.

This PR is now ready for review.

**Comment by axxel** [comment]
Just to have said it: it would be totally fine to have more than one commit (for more than one symbology) in one single PR :).

**Comment by gitlost** [comment]
Ah cool, was going to do one PR for a number of the 1-d barcodes which have trivial Symbology Identifiers, but not for others like ITF where it's slightly more involved. I do find though having separate commits in one PR error-prone on my part, especially with the way I'm doing it (porting from my local "diagnostics2" branch). Will give it a lash with the next PR...

**Pull request merged**
