### PR TITLE
ECI: add BINARY; refactor helper funcs; UnicodeBig fix

### PR DESCRIPTION
**Pull request by gitlost**
Adds ECI 899 `CharacterSet::BINARY`.

Refactors ECI code added to Aztec (https://github.com/nu-book/zxing-cpp/pull/218), Data Matrix (https://github.com/nu-book/zxing-cpp/pull/200) and MaxiCode (https://github.com/nu-book/zxing-cpp/pull/216) using new helper functions `CharacterSetECI::InitEncoding()` and `CharacterSetECI::OnChangeAppendReset()`.

Fixes ECI 25 `CharacterSet::UnicodeBig` (if someone's mad enough to use it) on non-Windows by using `TextUtfEncoding::AppendUtf16()` to account for surrogates.

Fixes `TextUtfEncoding::ToUtf(angleEscape)` on Windows to account for surrogates.

Fixes Shift JIS mapping NUL to undefined, and adds comment on it doing straight ASCII mapping rather than the more normal mappings of backslash and tilde to Yen sign and overline respectively (doing straight ASCII makes it compatible with e.g. MEBKM, which specifies ASCII for the URL field, but it probably should do the mappings if explicit ECI given in barcode).

Fixes `CharacterSetECI::ValueForCharset()` returning obsolete ECI 1 for ISO 8859-1, and returning 0 for not found. Some adjustments and fixes for ECI handling in PDF417 and QR Code encoders to account for this.

Additional unit tests added.

### CODE REVIEW

**Comment by axxel** [comment]
Thanks a lot. I'm more interested in the pixel counting part of the project. Nice to have someone look into the (boring?) details of the encoding side ;). I found 2 minor issues but decided to fix them after merging instead of bothering you...

I'm about to release 1.2. Is there something in your pipeline that you'd prefer to bring in before that? (I'm not really in a hurry.)

**Comment by gitlost** [comment]
Hi, thanks, yes enjoy the boring side lol - I've got ECI for PDF417 next, hopefully tomorrow, but nothing that would hold up a release...

**Comment by axxel** [comment]
To praise your work even more: both issues I thought I spotted were in fact none :).

PDF417 is the last in the ECI saga, right? Then I'll definitively wait, so we can claim ECI support across the board as news.

**Comment by gitlost** [comment]
Yes PDF417 is the last, though the QR ECI treatment could also do with some tweaks (sensitive topic though)...

**Pull request merged**
