### PR TITLE
2nd attempt at fixing #30

### PR DESCRIPTION
**Pull request by axxel**
Disclamer: I still did not prove that the new code makes it impossible to end up in an endless loop again.

### CODE REVIEW

**Comment by bommo1** [comment]
2nd attempt looks good. thanks!

**Comment by bommo1** [comment]
It took me more this time but here it is:

bug2

**Comment by bommo1** [comment]
@axxel I've added this hack on my side to avoid the rare cases when the problem occurs:

PointI old_next_p(-1, -1);
do {
   ...
   PointI next_p = round(p);

   if (old_next_p.x != -1 && old_next_p == next_p) {
      return false; // it staled; exit to avoid endless loop
   }
   old_next_p = next_p;
   ...

**Comment by axxel** [comment]
Thanks for the feedback. I discarded your approach when first thinking about a fix, because my gut feeling told me, I'd have to check a hole history of points. I considered that to be too complex and expensive. And it'd still be a 'hack', too. But your example helped me fix a corner case that I overlooked before.
After having spend even more time working on this, I would now be surprised if you found yet another example. Please surprise me! ;)

**Pull request merged**
