### PR TITLE
Add multi-file, one line option, non-graphical formatting to examples/ZXingReader

### PR DESCRIPTION
**Pull request by gitlost**
Adds multi-file handling and `-1` one line option to `example/ZXingReader`, and formats any non-graphical characters in the text into angle brackets (e.g. a linefeed becomes `<LF>`).

Also renames `Extension` -> `Add-on` (the standard name) and puts the actual value in quotes, with the formatted value appended (as interpretation can vary).

Removes the `_hints.requireEanAddOnSymbol()` check from `ODMultiUPCEANReader` when setting UPC_EAN_EXTENSION metadata so that it gets set if present anyway. I notice the check was added [here](https://github.com/nu-book/zxing-cpp/commit/10854f5edd73d18774cb8cda6bede3094a886363#diff-030e736c55f5432ae3f6e18016e565fb51ecc2240fe1c0fcedaf0d51ff75d4baR340) but it doesn't appear to be necessary.

### CODE REVIEW

**Comment by axxel** [comment]
* That `ODMultiUPCEANReader` looks like a true bug-fix, nice.
 * I get the value of the multi-file support (I was using the `ReaderTest` binary for that...)
 * I was first skeptical of the `-1` choice, but the man page of `ls` convinced me ;)
 * I'm (still) skeptical of the value of the `FormatText` function. I'd like to keep that file as simple as possible (it is a demo tool to show the API). What do you need that for? Is that the 'standard' way to do it (where is that code coming from)?
 * Why modify the locale?
 * That '+' <Add-on> approach seems non-standard to me. Any prior art for that?

**Comment by gitlost** [comment]
Re `FormatText`, it's needed to make the one line option work. Also printing invisible characters to the console is not very useful. 

There's no standard way I know of of showing non-graphics, the choice here was based on that used in the GS1 General Specifications for group separators, `<GS>`. Alternative suggestions welcome.

The code is my own, the names of the ASCII chars are the standard abbreviations.

Re locale, it's needed to make `iswgraph()` work, as the default is "C" (I'll add a comment stating this).

Re"+", again there's no standard that I know of. "+" is used by Zint. BWIPP uses a space. TEC-IT uses nothing (separate symbology). Zint's "+" seems like a natural choice to me, suggesting "add-on". Alternatives welcome.

Re keeping it simple, the motivation here is to make it a useful diagnostic tool, which is what I use it for. I don't think this makes it particularly bloated, but if you like I can split it off into e.g. "examples/ZXingReaderDiagnostic".

Thanks for reviewing, appreciate it.

**Comment by axxel** [comment]
> Re `FormatText`, it's needed to make the one line option work. Also printing invisible characters to the console is not very useful.

But you are calling `FormatText` also in the multi-line/default output. Also, I'd argue that printing a CR/LR character on the console is indeed very useful (thinking of those QRCodes with vCard data). What type of input do you have that actually contains text with non-printable characters?

> There's no standard way I know of of showing non-graphics, the choice here was based on that used in the GS1 General Specifications for group separators, `<GS>`. Alternative suggestions welcome.
> 
> The code is my own, the names of the ASCII chars are the standard abbreviations.

Thanks for the explanation. I don't have a better suggestion.

> Re locale, it's needed to make `iswgraph()` work, as the default is "C" (I'll add a comment stating this).

According to the spec (https://en.cppreference.com/w/cpp/string/wide/iswgraph) the locale influences the behavior but it is not required to be set to something specific to make iswgraph work. I guess you'd like to see printable utf8 characters on your console? Is there a sample in our testing set that shows the issue?

> Re"+", again there's no standard that I know of. "+" is used by Zint. BWIPP uses a space. TEC-IT uses nothing (separate symbology). Zint's "+" seems like a natural choice to me, suggesting "add-on". Alternatives welcome.

I see. I would have gone for a simple ' ', I guess, because that is how you'd read it printed on the symbol. Do you require this add-on text in your one-line output?

> Re keeping it simple, the motivation here is to make it a useful diagnostic tool, which is what I use it for. I don't think this makes it particularly bloated, but if you like I can split it off into e.g. "examples/ZXingReaderDiagnostic".

I'd suggest to add another command line parameter (e.g. '-escape') that explicitly enables the `FormatText` functionality and also move that code over to the `TextUtfEncoding` namespace either into an extended `std::string ToUtf8(const std::wstring& str, bool escapeNonGraphicalChars = false);` or a separate `std::string ToUtf8(const std::wstring& str, bool escapeNonGraphicalChars);`

> Thanks for reviewing, appreciate it.

Thanks for helping improve the code :).

**Comment by gitlost** [comment]
Re non-printable chars, good point about vCards, have made it an option `-escape` as suggested, with the exception that `-1` always escapes.

Non-printables occur in a number of situations, the most obvious being GS1 data with `<GS>` separators, and Maxicodes using ANSI MH10 Format "01" Version "96" `[)><RS>01<GS>96...<EOT>`.

Re `FormatText` have moved it as suggested to `TextUtfEncoding::ToUtf8(const std::wstring& str, const bool angleEscape)` and added a unit test for it re `std::isgraph()` - discovered a bug (off-by-one index) in the original version in the process.

Re add-on text, have changed the separator to space. It's not required, just nice info to have.

P.S. I see the test is failing on Windows/Mac - will fix it up tomorrow.

**Comment by axxel** [comment]
Nice touch with the unit test :). Please feel free to comment on my new Add-on handling issue/question.

**Comment by gitlost** [comment]
Not sure what's happening on Windows but have just `#ifdef`ed around the issues (would need to use something other than `std::iswgraph()` to do it properly).

Have also put my local hacked version on https://github.com/gitlost/zxing-cpp/tree/diagnostics so you can see what I'm aiming for re diagnostics (also some bug fixes). Future PRs will be cleaned up versions of the code there.

**Comment by axxel** [comment]
You seem to be seriously engaged in diagnosing issues with the decoders? Are there specific issues you are having?

I appreciate your interest in improving the code. That said, your diagnosis infrastructure seems relative invasive. I have not looked at it enough to fully understand what you are trying to achieve but it seems, you'd like to have a kind of fancy "printf debugging" that can be enabled at runtime (in a release build). I don't see the value of that compared to something like the existing preprocessor based `PRINT_DEBUG` code that I use for debugging/development (yet). I definitively believe that code introspection and debugging facilities are well placed in code that is removed in release builds.

If you'd be interested in chatting about your plans and goals with the project, maybe we can schedule a phone call? I'm based in Germany, so UTC+1.

**Comment by gitlost** [comment]
It's not issues I'm having really, it's just that I'm using it as an excellent tool to determine differences in encodation when comparing Zint's output to that of other barcode generators and to examples in standards etc.

I'm fine with leaving out the diagnostics which is very invasive as you say. I'll just PR the additional handling (Structured Append, Reader Initialization, ECI) and any bug fixes.

Thanks for offering to chat, feel free to email me.

**Comment by axxel** [comment]
After my recent change regarding Structured Append, I remembered that you had prepared something for the DataMatrix decoder in your branch. I just had another look at your code and wanted to ask whether you still plan on providing that as a separate PR?

I noticed that you introduced a std::string "id" field. I thought about as well because of the PDF417 decoder but was not sure the "fileId" was supposed to be that. Was that also your guess or do you have some definitive information? In that case I'd like to merge the `parity` with the `id` field and make it a string. For the QRCode this would be the equivalent field, even if it happens to have some more meaning.

About the `eci` field: if the code-page is switched somewhere in between, then the client code would need to do the whole decoding again based on the `rawBytes` after all symbols are detected, right? That would be pretty impractical...

**Comment by gitlost** [comment]
Hi yes I still have plans on providing a number of PRs but got distracted by other things. Also wasn't sure of what the intention regarding metadata was and looking at the recent changes I see it's to replace it mostly with direct `Result` fields, which is great.

Re making Structured Append "id" a string, this was driven primarily by Aztec Code, which uses an alphanumeric id. PDF417's "fileId" is numeric only, but of variable length (base 900 according to spec, so the current decoding here and upstream needs changing) so is also best represented as a string. So merging the `parity` (QR specific) with `id` and making it a string sounds good to me.

Re Structured Append `eci` field, any spec I've seen which supports both ECI and Structured Append states that the ECI can span symbols, which is problematic as you say, and any client code would have to set the initial ECI on affected symbols and re-decode if scanned out of sequence. Perhaps some extra info and/or helper functions could be added to assist with that...

(By the by my preference for the field names would be to drop the "symbol" prefix and use `id`, `sequenceNumber` and `totalNumber`.)

**Comment by gitlost** [comment]
Re ECI spanning symbols, was wrong about it always being the case - QR requires each symbol to have an ECI after the Structured Append (ISO/IEC 18004:2015 7.4.2.4), so that's fine. ECI spanning applies to Aztec, Data Matrix, MaxiCode and PDF417 of the supported barcodes (DotCode is another example).

**Comment by axxel** [comment]
Re StructuredAppend id: I'll do that then soonish. Best to wait with your DM PR with this regard. I did also some code cleanup and additional tests in DMDecoder.cpp (inspired by your branch), which will conflict with your changes.

Re StructuredAppend ECI: would you please add this information about QR vs. all other codecs in a comment at an appropriate place? It's so annoying that those specs are not public...

Re `sequenceNumber` is that term something 'official' coming up in the specification?

**Comment by gitlost** [comment]
Re StructuredAppend ECI info, yes, will do so. Need to do a fully worked example of dealing with out-of-sequence symbols with spanning ECIs, to see how feasible this all is, so will be a bit of a way off... also will be adding ECI support to Aztec and PDF417 first...

Re `sequenceNumber` it's not really official, though it seems to be a more common term. Also I think it would be best if it is 1-based, which sequence number suggests, whereas index suggests 0-based. Not that important obviously...

**Comment by axxel** [comment]
I'm done with the mentioned DMDecoder and StructuredAppend/Id changes.

The naming is indeed not quite straight forward. I felt the urge to give the 3 properties some connection. I considered
 * having a `StructuredAppendInfo Result::structuredAppend()` member, which I found unnecessarily complicating the interface
 * naming them `structruredAppendIndex`, etc., which I found too verbose
 * using the `symbol` prefix, which is also not obviously the 'correct' choice...

Since this is an API (not a user application) I'd argue that `index` starting at `0` as opposed to `sequenceNumber` is the right choice here.

**Comment by gitlost** [comment]
Yes "Structured Append" is tediously verbose. How about "sequence"? Then `sequenceId`, `sequenceIndex` (agree that 0-based more C++y), and `sequenceSize` (instead of "count" by analogy with std:string etc).

**Comment by axxel** [comment]
I had a look at the specs: DM and QR call the index part "position of the symbol" and the count part "total number of symbols", PDF calls it "Segment Index" and "Segment Count".

The index part is clearly a property of the symbol, the id/parity part is a property of the sequence and the count can be either or depending on the term (count vs size). Putting all 3 in the same 'namespace' clashes either way. Maybe my urge to 'connect' them is the wrong priority. I also added the `isStructuredAppendSymbol()` which already left the namespace (because I saw no way to make that also fit...).

Thinking more about it, I see now these 3 alternatives:
 1) `symbolIndex, symbolCount, symbolId, isStructuredAppendSymbol, isLastStructuredAppendSymbol` (current code)
 2) `sequenceIndex, sequenceSize, sequenceId, isPartOfSequence, isLastInSequence`
 3) `symbolIndex, symbolCount, sequenceId, isPartOfSequence, isLastInSequence`

And even though `sequenceIndex` feels wrong, I have to admit that 2) 'looks' nicest.... arghhh. Your chance to double down on your 'sequence' suggestion. If anyone else want's to chime in, now is the time...

**Comment by gitlost** [comment]
Ha I'd like to double down on "sequence" (which I got from the Aztec spec) but keep "StructuredAppend"  for the helpers so

- `sequenceIndex`, `sequenceSize`, `sequenceId`, `lastECI`, `isStructuredAppendSymbol`, `isLastStructuredAppendSymbol`

This splits the namespace like 1 and 3 but unless `structuredAppend` is used throughout I don't see a way around that.
```
	/**
	 * @brief sequenceSize number of symbols in a structured append context.
	 *
	 * If this is not part of a structured append set of symbols, the returned value is -1.
	 * If it is a structured append symbol but the total number of symbols is unknown, the
	 * returned value is 0 (see PDF417).
	 */
	int sequenceSize() const { return _sai.sequenceSize; }

	/**
	 * @brief sequenceIndex the 0-based index of this symbol in a structured append set of symbols.
	 */
	int sequenceIndex() const { return _sai.sequenceIndex; }

	/**
	 * @brief sequenceId id to check if a set of symbols belongs to the same structured append set.
	 *
	 * If the symbology does not support this feature, the returned value is empty (see MaxiCode).
	 * For QR Code, this is the parity integer converted to a string.
	 * For PDF417, this is the "fileId" numeric string.
	 */
	std::string sequenceId() const { return _sai.sequenceId; }

	/**
	 * @brief lastECI Character set ECI in effect at end of symbol if part of a structured append set.
	 */
	std::string lastECI() const { return _sai.lastECI; }

	bool isLastStructuredAppendSymbol() const { return sequenceSize() == sequenceIndex() + 1; }
	bool isStructuredAppendSymbol() const { return sequenceSize() > -1; }

	/**
	 * @brief symbologyIdentifier Symbology identifier "]sm" ("s" is symbology, "m" modifier).
	 */
	const std::string& symbologyIdentifier() const {
		return _symbologyIdentifier;
	}

	/**
	 * @brief readerInit Set if Reader Initialisation/Programming symbol.
	 */
	bool readerInit() const {
		return _readerInit;
	}
```

I agree that `sequenceIndex` should logically be `symbolIndex` but that breaks up the namespace too much as you suggest.

My main objection is to `symbolId` and its similarity to `symbologyIdentifier`, given that that will be introduced by https://github.com/nu-book/zxing-cpp/issues/214. But I don't want to bikeshed this to death, so whatever you decide is fine by me...

(Yes the `lastECI` business has yet to be proven...)

**Pull request merged**
